name: Test Self-Hosted Runner

on:
  workflow_dispatch:

jobs:
  test_runner:
    runs-on: ubuntu-latest #  This is a placeholder, your runner likely uses a different label.
    steps:
      - name: Check Runner Availability
        run: echo "Hello from the self-hosted runner!"
      - name: Get Environment Variables
        run: |
          echo "GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}"
          echo "USER: ${{ env.USER }}"
      - name: Test Network Connectivity
        run: |
          ping -c 3 google.com  # Or any public website
          if [ $? -eq 0 ]; then
            echo "Network connectivity OK"
          else
            echo "Network connectivity FAILED"
            exit 1
          fi
