name: Test Connectivity

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  connectivity-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check internet connectivity with curl
        run: |
          echo "Testing internet connectivity..."
          if curl -s --head https://google.com | grep "200 OK" > /dev/null; then
            echo "Internet connection is working."
          else
            echo "Internet connection failed."
            exit 1
          fi
